config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'
  get 'home/trash_em'
  get 'home/trash_em_all'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def trash_em
      @trash_em = List.where(:completed => true).destroy_all  
      redirect_to root_url, notice: 'All marked items were succesfully deleted.'
  end

  def trash_em_all
      @trash_em_all = List.all.destroy_all  
      redirect_to root_url, notice: 'All items were succesfully deleted.'
  end  

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @list = List.new
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_url, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_url, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'lists/navbar' %>
  <div class="container">
    <%= render 'flash' %>
    <body>
      <%= yield %>
    </body>
  </div>
</html>

app/views/lists/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
	<div class="alert alert-warning alert-dismissible">
		<button class="close" data-dismiss="alert">
			<!-- <i class="glyphicon glyphicon-remove-circle"></i> -->
			<small><sup>x</sup></small>
		</button>
		<%= content_tag(:div, msg) %>
	</div>
<% end %>			

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :completed, class: 'form-check-input' %>
    <%= form.label :completed, class: 'form-check-label' %>
  </div>

  <div class="actions">
    <%= form.submit "Update todo item", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/lists/_form_index.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inline my-2 my-lg-0">
    <!-- Add new list item : --> 
    <% form.label :description %>
    <%= form.text_field :description, class: "form-control mr-sm-2" %>
    <%= form.submit "Add ToDo item", class: "btn btn-outline-secondary my-2 my-sm-0" %>
  </div>
<% end %>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Todo List", root_path , class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">


    </ul>
   <%= render 'form_index', list: @list %>
   <!--
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
   -->
  </div>
</nav>

app/views/lists/edit.html.erb
<h1>Edit todo item</h1>

<br/>
<div class="card" style="width: 18rem;">
  
  <div class="card-body">
  	<%= render 'form', list: @list %>
  </div>
</div>
<br/><br/>

<% link_to 'Show', @list %> 
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->


<table class="table table-bordered">
  <!--
  <thead>
    <tr>
      <th>Todo item</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  -->

  <tbody>
    <% @lists.each do |list| %>

      <% if list.completed %>
      <tr class="table-secondary">
        <td class="striker"><%= link_to list.description, edit_list_path(list) %><% list.description %>
        </td>
        <td>
            <%= form_for(list) do |f| %>
              <%= f.text_field :description, type: 'hidden' %>
              <%= f.check_box :completed, :checked => false, :style => 'visibility:hidden' %>
              <%= f.submit "Uncross", class: 'btn btn-outline-secondary btn-sm' %>
            <% end %>  
        </td>
        <td>
          <% link_to 'Show', list %>
          <% link_to 'Edit', edit_list_path(list) %>
          <%= link_to 'Delete', list, class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?', class: 'btn btn-danger' } %>
        </td>
      </tr>
      <% else %>
      <tr>
        <td><%= link_to list.description, edit_list_path(list) %><% list.description %>
          
        </td>
        <td>
            <%= form_for(list) do |f| %>
              <%= f.text_field :description, type: 'hidden' %>
              <%= f.check_box :completed, :checked => true, :style => 'visibility:hidden' %>
              <%= f.submit "Cross off", class: 'btn btn-outline-secondary btn-sm' %>
            <% end %>  
        </td> 
        <td>
          <% link_to 'Show', list %>
          <% link_to 'Edit', edit_list_path(list) %>
          <%= link_to 'Delete', list, class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Delete marked items', home_trash_em_path, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Delete all items', home_trash_em_all_path, data: { confirm: 'Are you sure?' } %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Todo item:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @list.completed %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>